= Spiracle

Spiracle is an insecure web application used to test system security controls. 

It can be used to read/write arbitrary files and open network connections.
The application is also vulnerable to numerous other vulnerabilities such as:

* SQL Injection (CWE-89)
* XSS (CWE-79)
* CSRF (CWE-352)
* Path Traversal (CWE-22)
* Deserialization (CWE-502)
* and many more...

CAUTION: Due to its insecure design, this application should NOT be deployed on an unsecured network or system.

This application has been tested on the following application servers:

* Apache Tomcat 5.0.x

Your mileage may vary with other application servers.

== Installation

* Download pre-built `spiracle.war` file from the releases page: https://github.com/waratek/spiracle/releases

=== Tomcat

* Copy the war file to the `$CATALINA_HOME/webapps/` directory.

=== Database setup

If you would like to run the SQL injection tests, the database should be populated as follows. Data files are available in the web applications `spiracle/conf/` directory after the `spiracle.war` file has been deployed and exploded.

==== Oracle

. Ensure that the link:http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-112010-090769.html[Oracle Database JDBC Driver] (ojdbc6.jar) is installed in the applications `WEB-INF/lib/` directory after the `spiracle.war` file is exploded on first run.
. Import the data:
+
----
$ sqlplus SYS/password@//127.0.0.1:1521/XE AS SYSDBA < setupdb_oracle.sql
----
+
NOTE: This will create a user `test` with password `test`. You should adjust usernames and/or connection URLs dependent on your environment
+
. Configuration parameters for the Oracle JDBC connection are defined in `conf/Spiracle.properties`:
+
----
c3p0.classname=oracle.jdbc.driver.OracleDriver
c3p0.url=jdbc:oracle:thin:@localhost:1521:XE
c3p0.username=test
c3p0.password=test
----

NOTE: It may be necessary to restart your application server after deploying the `ojdbc6.jar` or updating database configuration.

==== MySQL
. Import the data:
+
----
$ mysql -u root -p test < setupdb_mysql.sql
----
+
NOTE: This will create a user `test` with password `test`. You should adjust usernames and/or connection URLs dependent on your environment
+
. Configuration parameters for the MySQL JDBC connection are defined in `conf/Spiracle.properties`:
+
----
c3p0.classname=com.mysql.jdbc.Driver
c3p0.url=jdbc:jdbc:mysql://localhost:3306/test
c3p0.username=test
c3p0.password=test
----

NOTE: Spiracle is bundled with MySQL Connector 3.1.14. If this version is not compatible with your MySQL installation replace `mysql-connector-java-5.1.34.jar` under `WEB-INF/lib/` with a compatible version.

== Running

After deployment, the Spiracle application will be available at:

----
http://ip:port/spiracle/
----

== Building

Prerequisites:

* Java >= 1.4
* Apache Maven
* link:http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-112010-090769.html[Oracle Database JDBC Driver] (ojdbc6.jar)
* link:https://www.oracle.com/technetwork/apps-tech/jdbc-10201-088211.html[Java 4 Oracle Database JDBC Driver] (ojdbc14.jar)
* link:http://www-01.ibm.com/support/docview.wss?uid=swg21363866[Java 4 DB2 JDBC Driver] (db2jcc.jar v3.69.66 is good)

The connection pooling dependencies for Java 4 are not in Maven, and need to be manually downloaded and installed into your local Maven repository.

 - Download https://master.dl.sourceforge.net/project/c3p0/c3p0-bin/c3p0-0.9.2/jdk14-versions/c3p0-0.9.2-jdk14.bin.zip
 - Unzip the downloaded file
 - The 2 required jar files are in the lib directory
 - To install into a local Maven repository:

    $ mvn install:install-file -DgroupId=com.mchange -DartifactId=c3p0 -Dversion=0.9.2-j14 -Dpackaging=jar -Dfile=c3p0-0.9.2-jdk14.jar

    $ mvn install:install-file -DgroupId=com.mchange -DartifactId=mchange-commons-java -Dversion=0.2.3.3-j14 -Dpackaging=jar -Dfile=mchange-commons-java-0.2.3.3-jdk14.jar

If you wish to use the database features, ensure that the appropriate database JDBC driver file is available under `./src/main/webapp/WEB-INF/lib`

To build the Spiracle Test Application WAR file, run:

 $ mvn package -Dversion.webxml=24 -Dversion.jdk=1.4


To clean the build infrastructure, run:

 $ mvn clean

The WAR file will be output to:

 ./target/spiracle.war

== License

----
Copyright 2018 Waratek Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
----

